# Generated by Django 5.2.2 on 2025-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'Drinks'), ('chips', 'Chips'), ('sweets', 'Sweets'), ('food', 'Food')]),
        ),
    ]
