# Generated by Django 5.2.2 on 2025-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
